name: CI/CD Pipeline for Selenium with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven tests
      - name: Run Maven tests
        run: mvn clean test -DsuiteXmlFile=testng.xml -Dallure.results.directory=target/allure-results

      # Step 5: Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      # Step 6: Publish Allure Report
      - name: Publish Allure Report
        uses: allure-framework/actions-allure-report@v2
        with:
          results-dir: target/allure-results
          report-dir: target/allure-report
