name: CI/CD Pipeline for Selenium with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Install Maven using Chocolatey
    - name: Install Maven using Chocolatey
      run: choco install maven

    # Step 4: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: C:\tools\apache-maven\apache-maven-3.8.1\lib
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 5: Install Allure (if needed)
    - name: Install Allure
      run: |
        curl -s https://raw.githubusercontent.com/allure-framework/allure2/master/allure-jenkins-plugin/install.sh | bash

    # Step 6: Run Maven tests and generate Allure results
    - name: Run Maven tests and generate Allure results
      run: mvn clean verify -Dallure.results.directory=target/allure-results

    # Step 7: Generate Allure Report
    - name: Generate Allure Report
      run: mvn allure:report

    # Step 8: Upload Allure Report as an artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven
